FROM __TAG__

ARG PKG_NODE

ARG PKG_OS

ARG PKG_ARCH

RUN __DEPENDENCIES__

ENV PKG_CACHE_PATH=/fetched

RUN git clone -b fork --single-branch https://github.com/n1ru4l/pkg-fetch.git /build
WORKDIR /build
RUN yarn && yarn run babel
RUN mkdir -p /fetched

RUN MAKE_JOB_COUNT=2 yarn run bin ${PKG_NODE} ${PKG_OS} ${PKG_ARCH}

CMD ["sh"]